version: "3.4"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.38.0/24

services:
  main_service:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    ports:
      - 8081:8080
  logs_collector:
    image: main_image:latest
    volumes:
      - ./logs:/logs
    command: cat logs/logs.txt